### ISSUE TITLE
Display Errors back to the Caller

### ISSUE THREAD

**Issue by TravisBoatman** [danjagnow/ArgentPonyWarcraftClient#38]
Currently if you were to search for a spell, character, realm, or anything that doesn't exist the program will throw an exception. In `WarcraftClient.cs` line 955 `response.EnsureSuccessStatusCode();`. Although Blizzard's API will have the status code 404 it will still send a response back like so...

```
{
    "status": "nok",
    "reason": "unable to get spell information."
}
```
It would be nice to be able to send that information back to the caller so that if needed they can display the specific error reason. This is my proposal on how to make it happen and would love some feedback on it.

First create an `Error.cs` class with the `Status` and `Reason` properties. Then have all models inherit from it. The caller method can now check if the `Status` property is null, if so it succeeded. If not then they can grab the `Reason` property and display it back to the end-user.

This way feels a bit clunky, I don't really like it but it works.

**Comment by danjagnow** [comment]
I would definitely want to capture those error details, but I think I might prefer to still throw an exception instead of adding properties to the return type that are not needed in normal operation.  As a side note, it appears that the API is having some issues.  I logged them here:

https://us.battle.net/forums/en/bnet/topic/20759518166#1

**Comment by TravisBoatman** [comment]
Would creating a wrapper be the best way? For example...

```
puiblic class Response<T>
{
    public string Success { get; }
    public Error Error { get; }
    public T Content { get; }
}
```

Then in action...
```
var warcraftClient = new WarcraftClient(_apiKey);
var response = await warcraftClient.GetSpellAsync(805644444);
if (!response.Success)
{
    var status = response.Error.Status;
    var reason = response.Error.Reason;
}
else
{
    return response.Content;
}
```

**Comment by danjagnow** [comment]
Most applications will have a global error-handling mechanism, and they should be wrapping calls to external services in a try-catch block anyway, so I think that throwing an exception with a higher level of detail is a good approach.  I created pull request #39 with a draft of that approach.  I'm not too worried about breaking existing users yet because there aren't many of them.  :-)  Feedback on this approach would be appreciated.
