### ISSUE TITLE
Summary Docs Convention Proposal

### ISSUE THREAD

**Issue by TravisBoatman** [danjagnow/ArgentPonyWarcraftClient#41]
This is purely my personal opinion but I prefer to have summary docs to be indented like in `InternalHttpClient.cs`. So I wanted to get your opinion on the matter to.

**Comment by danjagnow** [comment]
I've seen the indentation for the XML comments done both ways.  I usually leave just a single space because it requires fewer keystrokes, but I can see how the extra indentation makes the summary stand out a bit more.  I have no objection to changing the convention.  Feel free to make formatting updates.  I did a brief search, and I don't see an EditorConfig setting for that.
